### ISSUE TITLE
Future .NET 6 Support

### ISSUE THREAD

**Issue by viceroypenguin** [linq2db/linq2db#2977]
There are several new APIs on `IQueryable<T>` coming out in .NET 6 that we should address at some point, whether to support or expressly reject. This is an initial issue to start discussing. 

- [ ] dotnet/runtime#28776 - `IQueryable<T>.ElementAt(Index)` and company
- [ ] dotnet/runtime#43702 - `IQueryable<T>.Zip()` (two and three-arity versions)
- [ ] dotnet/runtime#27449 - `IQueryable<T>.Chunk(int)`
- [ ] dotnet/runtime#20064 - `IQueryable<T>.*OrDefault()` new versions where default value can be provided
- [ ] dotnet/runtime#27183 - `IEnumerable<T>.TryGetNonEnumeratedCount()` we can probably just always return false for this one, but we should still explicitly support it

**Comment by jogibear9988** [comment]
https://github.com/dotnet/runtime/issues/27687

**Comment by viceroypenguin** [comment]
Thanks @jogibear9988

**Comment by worldbeater** [comment]
Guessing we should create a `DistinctBy` builder similar to https://github.com/linq2db/linq2db/blob/11406a329f3904e15671348ce52f1a098c927949/Source/LinqToDB/Linq/Builder/DistinctBuilder.cs and then register it inside the `ExpressionBuilder`: https://github.com/linq2db/linq2db/blob/f6ae79d6138b295f29b37f6696264ca8793a9bc6/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs#L28-L32

Worth noting that folks usually implement workarounds for `DistinctBy` queries like this:
```csharp
var distinct = cars
  .GroupBy(car => car.CarCode)
  .Select(group => group.First())
  .ToList();
```

**Comment by jogibear9988** [comment]
Should also Default Types for SQL Types be changed?

Time => TimeOnly instead of TimeSpan (wich is clearly wrong)
Date => DateOnly

**Comment by MaceWindu** [comment]
@jogibear9988, what is `default type` here? I would say we should switch to those types in scaffold (with compatibility switch). Anything else?

**Comment by jogibear9988** [comment]
I don't understand the question. 
As I wrote, default type for TimeOnly should be Time in SQL I think, and for DateOnly it should be Date. Or am I wrong?
